@api = http://localhost:8000/api/usuario

{{api}}

### add usuario
POST http://localhost:8000/api/usuario
Content-Type: application/json

{
    "nombre": "Pablo Fernando",
    "ape_paterno":"Cornejo",
    "ape_materno":"Hidalgo",
    "telefono":"933267819",
    "correo_electronico":"pabloFer@gmail.com",
    "contrasenia":"1678DRTW",
    "num_documento":"73962897",
    "IdEstadoUsuario":1,
    "IdDocumento":1,
    "IdRol":3
  
}

### get usuario
{{api}}/2

